### ISSUE TITLE
[Bug] FieldIdentifier only supports simple member accessors (fields, properties) of an object.

### ISSUE THREAD

**Issue by sion-corn** [Blazored/Typeahead#170]
I am trying to bind BlazoredTypeahead to a list item, but I am getting the following error:

```
Error: System.ArgumentException: The provided expression contains a InstanceMethodCallExpression1 which is not supported. FieldIdentifier only supports simple member accessors (fields, properties) of an object.
   at Microsoft.AspNetCore.Components.Forms.FieldIdentifier.ParseAccessor[T](Expression`1 accessor, Object& model, String& fieldName)
   at Microsoft.AspNetCore.Components.Forms.FieldIdentifier.Create[TField](Expression`1 accessor)
   at Blazored.Typeahead.BlazoredTypeahead`2.OnInitialized()
   at Microsoft.AspNetCore.Components.ComponentBase.RunInitAndSetParametersAsync()
```

My code:
```
<div id="divItems">
    @for (int i = 0; i < Model.Items.Count; i++)
    {
        var iCopy = i; //see https://stackoverflow.com/a/56426146/323447
        <div class="row g-3 mb-2">
            <div class="col-12" style="display:flex;">
                <div class="input-group mr-2">
                    <BlazoredTypeahead SearchMethod="@SearchItemName"
                                       @bind-Value="@Model.Items[iCopy]"
                                       Placeholder="Start typing to check if item already exists..."
                                       class="form-control text-truncate"
                                       Debounce="500">
                        <SelectedTemplate Context="item">
                            @item.Name
                        </SelectedTemplate>
                        <ResultTemplate Context="item">
                            @item.Name
                        </ResultTemplate>
                    </BlazoredTypeahead>
                </div>
                <button type="button" class="btn btn-outline-danger" @onclick="(() => RemoveItem(iCopy))"><span class="material-icons">clear</span></button>
            </div>
        </div>
    }
    <div class="row g-3">
        <div class="col-12">
            <button type="button" class="btn btn-outline-success" title="Add another" @onclick="AddItem" disabled="@addItemButtonDisabled"><span class="material-icons">playlist_add</span></button>
        </div>
    </div>
</div>
```
Is there a way to bind to a list item instead of an object?

**Comment by chrissainty** [comment]
Hi @sion-corn, unfortunately I don't this is anything to do with the Typeahead, this error is coming from the framework. I'm surprised this doesn't work to be honest. I've just had a quick search and it seems there have been a few people dealing with this error or versions of it.

I would suggest raising an issue on the ASP.NET Core repo and speaking to the team about it.

**Comment by sion-corn** [comment]
Hey @chrissainty, yeah, I saw that it's a framework limitation. Seems like [someone raised this issue already](https://github.com/dotnet/aspnetcore/issues/12000), but the MS team let it die on the vine...

**Comment by chrissainty** [comment]
No problem, @sion-corn. I'm going to close this issue as there isn't any work we can do here.
